version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 20
    groups:
      appium-webdriver:
        patterns:
          - "Appium.WebDriver"
      selenium-webdriver-support:
        patterns:
          - "Selenium.WebDriver"
          - "Selenium.Support"
      extentreports:
        patterns:
          - "ExtentReports"
      microsoft-net-test-sdk:
        patterns:
          - "Microsoft.NET.Test.Sdk"
      nlog:
        patterns:
          - "NLog"
      nunit:
        patterns:
          - "NUnit"
      nunit-console-runner:
        patterns:
          - "NUnit.Console"
          - "NUnit.ConsoleRunner"
      nunit3testadapter:
        patterns:
          - "NUnit3TestAdapter"
      refit:
        patterns:
          - "Refit"
      selenium-webdriver-chromedriver:
        patterns:
          - "Selenium.WebDriver.ChromeDriver"
      dotnet-selenium-extras:
        patterns:
          - "DotNetSeleniumExtras.WaitHelpers"
      specflow:
        patterns:
          - "SpecFlow"
