version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      appium-webdriver:
        patterns:
          - "Appium.WebDriver"
      selenium-webdriver:
        patterns:
          - "Selenium.WebDriver"
      extentreports:
        patterns:
          - "ExtentReports"
      microsoft-net-test-sdk:
        patterns:
          - "Microsoft.NET.Test.Sdk"
      nlog:
        patterns:
          - "NLog"
      nunit:
        patterns:
          - "NUnit"
      nunit3testadapter:
        patterns:
          - "NUnit3TestAdapter"
      refit:
        patterns:
          - "Refit"
      selenium-support:
        patterns:
          - "Selenium.Support"
      selenium-webdriver-chromedriver:
        patterns:
          - "Selenium.WebDriver.ChromeDriver"
